services:
  app:
    image: vashirr01/esoteric-resources-app    # Changed this line from 'build:'
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=resources
      - SESSION_SECRET=${SESSION_SECRET}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=resources
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d resources"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
volumes:
  postgres_data:
networks:
  app-network:
    driver: bridge
